/**
 * Created by yinwk on 2017/5/11.
 */
const applicationFormMode = [{
    key: "familyName",
    value: "姓"
}, {
    key: "middleName",
    value: "中间名"
}, {
    key: "givenName",
    value: "名"
}, {
    key: "chineseName",
    value: "中国名"
}, {
    key: "countryOfCitizenship",
    value: "国籍"
}, {
    key: "gender",
    value: "性别"
}, {
    key: "dateOfBirth",
    value: "出生日期"
}, {
    key: "validUntil",
    value: "护照有效至"
}, {
    key: "placeOfBirth",
    value: "出生地"
}, {
    key: "passportNo",
    value: "护照号"
}, {
    key: "religion",
    value: "宗教"
}, {
    key: "marriageStatus",
    value: "婚姻状况"
}, {
    key: "occupation",
    value: "职业"
}, {
    key: "institutionOrEmployer",
    value: "学校或工作单位"
}, {
    key: "phone",
    value: "手机号码"
}, {
    key: "email",
    value: "邮箱"
}, {
    key: "homeCountryAddress",
    value: "本国住址"
}, {
    key: "zipCode",
    value: "邮编"
}, {
    key: "fax",
    value: "传真"
}, {
    key: "mailingAddress",
    value: "收件地址"
}, {
    key: "receiver",
    value: "收件人"
}, {
    key: "englishAbility",
    value: "英语能力"
}, {
    key: "chineseReading",
    value: "汉语阅读"
}, {
    key: "chineseSpeaking",
    value: "口语"
}, {
    key: "chineseListening",
    value: "听"
}, {
    key: "chineseWriting",
    value: "写"
}, {
    key: "otherLanguageAbility",
    value: "其他语言能力"
}, {
    key: "otherLanguage",
    value: "其他语言"
}, {
    key: "recommendedBy",
    value: "推荐单位（人）"
}, {
    key: "contactPerson",
    value: "联系人"
}, {
    key: "recommendAddress",
    value: "联系地址"
}, {
    key: "contactTel",
    value: "联系人手机"
}, {
    key: "majorOrStudy",
    value: "专业(方向)"
}, {
    key: "chinaContactName",
    value: "在华事务联系人"
}, {
    key: "chinaContactPhone",
    value: "在华事务联系人手机"
}, {
    key: "chinaContactEmail",
    value: "在华事务联系人邮箱"
}, {
    key: "chinaContactAddress",
    value: "在华事务联系人地址"
}, {
    key: "formName",
    value: "申请单标识名"
}, {
    key: "durationOfStudyFrom",
    value: "学习开始日期"
}, {
    key: "durationOfStudyTo",
    value: "学习结束日期"
}, {
    key: "financialResource",
    value: "经费来源"
}, {
    key: "category",
    value: "申请类别"
}, {
    key: "applyStatus",
    value: "申请单状态"
}];

module.exports = applicationFormMode;