/**
 * Created by yinwk on 2017/5/16.
 */
const PlaceHolder = {
    PLACEHOLDER_PHONE_VALUE: "请输入您的手机号码",
    PLACEHOLDER_EMAIL_VALUE: "请输入您的邮箱",
    PLACEHOLDER_POSTAL_ADDRESS_VALUE: "请输入您的邮件地址",
    PLACEHOLDER_FAMILY_NAME_VALUE: "请输入您的姓",
    PLACEHOLDER_MIDDLE_NAME_VALUE: "请输入您的中间名",
    PLACEHOLDER_GIVEN_NAME_VALUE: "请输入您的名字",
    PLACEHOLDER_CHINESE_NAME_VALUE: "请输入您的中国名字",
    PLACEHOLDER_PLACE_OF_BIRTH_VALUE: "请输入您的出生地",
    PLACEHOLDER_PASSPORT_NO_VALUE: "请输入您的护照号",
    PLACEHOLDER_OCCUPATION_VALUE: "请输入您的职业",
    PLACEHOLDER_INSTITUTION_OR_EMPLOYER_VALUE: "请输入您的学校或工作单位",
    PLACEHOLDER_HOME_COUNTRY_ADDRESS_VALUE: "请输入您本国的住址",
    PLACEHOLDER_ZIP_CODE_VALUE: "请输入邮编",
    PLACEHOLDER_FAX_VALUE: "请输入您的传真",
    PLACEHOLDER_MAILING_ADDRESS_VALUE: "请输入您的收件地址",
    PLACEHOLDER_RECEIVER_VALUE: "请输入收件人",
    PLACEHOLDER_OTHER_LANGUAGE_VALUE: "请输入您掌握的其他语言",
    PLACEHOLDER_RECOMMENDED_BY_VALUE: "请输入推荐单位",
    PLACEHOLDER_CONTACT_PERSON_VALUE: "请输入联系人",
    PLACEHOLDER_RECOMMEND_ADDRESS_VALUE: "请输入联系地址",
    PLACEHOLDER_CONTACT_TEL_VALUE: "请输入联系人手机号码",
    PLACEHOLDER_MAJOR_OR_STUDY_VALUE: "请输入您的专业(方向)",
    PLACEHOLDER_CHINA_CONTACT_NAME_VALUE: "请输入您的在华事务联系人",
    PLACEHOLDER_CHINA_CONTACT_PHONE_VALUE: "请输入您的在华事务联系人手机号码",
    PLACEHOLDER_CHINA_CONTACT_EMAIL_VALUE: "请输入您的在华事务联系人邮箱",
    PLACEHOLDER_CHINA_CONTACT_ADDRESS_VALUE: "请输入您的在华事务联系人地址",
    PLACEHOLDER_FORM_NAME_VALUE: "请输入您的申请单标识名"
};
module.exports = PlaceHolder;