/**
 * Created by yinwk on 2017/5/5.
 */
const Success = {
    LOGIN_SUCCESS_CODE: "000000",
    LOGOUT_SUCCESS_CODE: "000000",
    REGISTER_SUCCESS_CODE: "000000",
    STUDENT_SUCCESS_CODE: "000000",
    APPLICATION_SUCCESS_CODE: "000000",
    UPLOAD_SUCCESS_CODE: "000000",
    APPLICATION_STATUS_SUCCESS_CODE: "000000",
    MESSAGE_STATUS_SUCCESS_CODE: "000000",
    LOGIN_SUCCESS_MESSAGE: "登录成功",
    REGISTER_SUCCESS_MESSAGE: "注册成功,即将跳往登录页面",
    SAVE_STUDENT_INFORMATION_SUCCESS_MESSAGE: "个人信息保存成功",
    CHANGE_STUDENT_PASSWORD_SUCCESS_MESSAGE: "修改密码成功",
    ADD_APPLICATION_FORMS_SUCCESS_MESSAGE: "添加申请表成功",
    CHANGE_APPLICATION_FORMS_SUCCESS_MESSAGE: "修改申请表成功",
    ADD_APPLY_RELATIONS_SUCCESS_MESSAGE: "提交成功,已添加申请关系",
    EMAIL_VERIFY_SUCCESS_MESSAGE: "注意查收激活邮件",
    UPLOAD_IMAGE_SUCCESS_MESSAGE: "上传头像成功"
};
module.exports = Success;